export const mockData = [
  {
    id: '2',
    carrier: {
      CarrierId: 992,
      Name: 'Pobeda',
    },
    currency: {
      Code: 'RUB',
      Symbol: '₽',
    },
    destinationplace: {
      CityId: 'NYCA',
      CityName: 'New York',
      CountryName: 'United States',
      IataCode: 'JFK',
      Name: 'New York John F. Kennedy',
      PlaceId: 60987,
      SkyscannerCode: 'JFK',
    },
    originplace: {
      CityId: 'MOSC',
      CityName: 'Moscow',
      CountryName: 'Russia',
      IataCode: 'VKO',
      Name: 'Moscow Vnukovo',
      PlaceId: 88879,
      SkyscannerCode: 'VKO',
    },
    price: 21233,
    textInboundpartialdate: '2 April, 2021',
    textOutboundpartialdate: '6 March, 2021',
    time: '19:19',
  },
  {
    id: '3',
    carrier: {
      CarrierId: 992,
      Name: 'Pobeda',
    },
    currency: {
      Code: 'RUB',
      Symbol: '₽',
    },
    destinationplace: {
      CityId: 'NYCA',
      CityName: 'New York',
      CountryName: 'United States',
      IataCode: 'JFK',
      Name: 'New York John F. Kennedy',
      PlaceId: 60987,
      SkyscannerCode: 'JFK',
    },
    originplace: {
      CityId: 'MOSC',
      CityName: 'Moscow',
      CountryName: 'Russia',
      IataCode: 'VKO',
      Name: 'Moscow Vnukovo',
      PlaceId: 88879,
      SkyscannerCode: 'VKO',
    },
    price: 33333,
    textInboundpartialdate: '2 April, 2021',
    textOutboundpartialdate: '6 March, 2021',
    time: '13:19',
  },
  {
    id: '4',
    carrier: {
      CarrierId: 992,
      Name: 'Pobeda',
    },
    currency: {
      Code: 'RUB',
      Symbol: '₽',
    },
    destinationplace: {
      CityId: 'NYCA',
      CityName: 'New York',
      CountryName: 'United States',
      IataCode: 'JFK',
      Name: 'New York John F. Kennedy',
      PlaceId: 60987,
      SkyscannerCode: 'JFK',
    },
    originplace: {
      CityId: 'MOSC',
      CityName: 'Moscow',
      CountryName: 'Russia',
      IataCode: 'VKO',
      Name: 'Moscow Vnukovo',
      PlaceId: 88879,
      SkyscannerCode: 'VKO',
    },
    price: 44444,
    textInboundpartialdate: '2 April, 2021',
    textOutboundpartialdate: '6 March, 2021',
    time: '12:12',
  },
  {
    id: '5',
    carrier: {
      CarrierId: 992,
      Name: 'Pobeda',
    },
    currency: {
      Code: 'RUB',
      Symbol: '₽',
    },
    destinationplace: {
      CityId: 'NYCA',
      CityName: 'New York',
      CountryName: 'United States',
      IataCode: 'JFK',
      Name: 'New York John F. Kennedy',
      PlaceId: 60987,
      SkyscannerCode: 'JFK',
    },
    originplace: {
      CityId: 'MOSC',
      CityName: 'Moscow',
      CountryName: 'Russia',
      IataCode: 'VKO',
      Name: 'Moscow Vnukovo',
      PlaceId: 88879,
      SkyscannerCode: 'VKO',
    },
    price: 55555,
    textInboundpartialdate: '2 April, 2021',
    textOutboundpartialdate: '6 March, 2021',
    time: '11:11',
  },
];
