export const APP_SET_FLIGHTS = 'APP_SET_FLIGHTS';
export const APP_GET_FLIGHTS = 'APP_GET_FLIGHTS';
export const APP_SET_FAVORITE = 'APP_SET_FAVORITE';
export const APP_DELETE_FAVORITE = 'APP_DELETE_FAVORITE';
